server:
  port: 3344
spring:
  application:
    name: springcloud-study-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/maoxiaohai/SpringCloud.git
          search-paths: config-repo
          username: maoxiaohai
          password: MXHai123